Adds support for "begins_with" operator searches
aaronshaf/dynamodb-admin pull request #196
Opened 2022-01-30 06:11 UTC by sagarbaver

I've added support for issuing queries using the "begins_with" operator.
This change partially contributes towards resolving https://github.com/aaronshaf/dynamodb-admin/issues/66 and improves user experience.

2022-01-30 06:13 UTC, sagarbaver commented
@aaronshaf @rchl Please review. Thanks!

2022-01-30 07:11 UTC, rchl commented on lib/backend.js
> +            }
The code looks very repetitive. Can you clean this up a bit?

The `matchedKeySchema` variable can be initialized before the `if` block.
The `KeyConditionExpression.push` call can be done once after if/else checks if any filter is defined.

2022-01-30 20:30 UTC, rchl commented
The select box that lists `begins_with` doesn't fit the text when selected:
![Screenshot 2022-01-30 at 21 29 18](https://user-images.githubusercontent.com/153197/151716553-27a60d56-6ee1-4abd-abd2-ab722ff3bf68.png)

2022-01-30 20:44 UTC, rchl requested changes

2022-01-30 20:44 UTC, rchl commented on lib/backend.js
> +          const matchedKeySchema = indexBeingUsed !== undefined ? indexBeingUsed.KeySchema.find(
`indexBeingUsed` starts as `null` so this needs to be:
```suggestion
          const matchedKeySchema = indexBeingUsed !== null ? indexBeingUsed.KeySchema.find(
```
or just a truthy check like before.

2022-02-01 21:26 UTC, rchl approved these changes

2022-02-01 21:27 UTC, merged

2022-02-01 21:27 UTC, rchl commented
thanks!

2022-02-02 06:51 UTC, sagarbaver commented
@rchl @aaronshaf Could one of you please make these changes available on Docker Hub?
https://hub.docker.com/r/aaronshaf/dynamodb-admin/tags

2022-02-02 08:32 UTC, rchl commented
Updated