Resolves aaronshaf/dynamodb-admin#78 Delete/Purge multiple tables at once
aaronshaf/dynamodb-admin pull request #248
Opened 2022-04-29 10:41 UTC by relbns

Adding new features of deleting and purging all of the tables at once. 
this is a requested feature from open issue #78 

the buttons are located on the same row as the create button but aligned to the right. 
screenshot:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/85161279/165917295-01f0c6c1-6980-476e-aab9-a7fbeab300a5.png">

2022-04-29 11:06 UTC, rchl requested changes

2022-04-29 11:06 UTC, rchl commented on lib/backend.js
> +    try {
We don't need to explicitly use the try/catch block. `asyncMiddleware` takes care of that.

2022-04-29 11:06 UTC, rchl commented on lib/backend.js
> +  app.delete('/api/deleteAllTables', asyncMiddleware(async (req, res) => {
Not an issue but this is not very consistent route.
Maybe just `/tables` for deleting all and `/tables-prune` for pruning

2022-04-29 12:28 UTC, relbns commented on views/tables.ejs
> +          location.reload()
is this answering the problem?

response.text().then(text => {
            text && window.alert(text)
            location.reload()
          }

2022-04-29 12:31 UTC, rchl commented on views/tables.ejs
> +          location.reload()
```suggestion
          response.text().then(text => {
            window.alert(text)
            location.reload()
          })
```

2022-04-30 19:18 UTC, rchl approved these changes

2022-04-30 19:20 UTC, merged